export const images = {
  favicon: '/favicon.ico',
  logo: '/logo512.png',
  icons: {
    walletConnect: '/assets/images/icons/walletConnect.png',
    walletConnectPay: '/assets/images/icons/walletConnectPay.png',
    avatarDefault: '/assets/images/icons/avatarDefault.png',
    iconZalo: '/assets/images/icons/iconZalo.png',
    iconHome: '/assets/images/icons/iconHome.png',
    iconMyUser: '/assets/images/icons/iconMyUser.png',
    iconLoadingModal: '/assets/images/icons/iconLoadingModal.png',
    iconCheckBoxSelected: '/assets/images/icons/iconCheckBoxSelected.svg',
    iconCheckBox: '/assets/images/icons/iconCheckBox.svg',
    iconOptionPayment: '/assets/images/icons/iconOptionPayment.png',
    iconMomo: '/assets/images/icons/iconMomo.png',
    iconWarning: '/assets/images/icons/iconWarning.png',
    iconDiscount: '/assets/images/icons/iconDiscount.png',
    iconBill: '/assets/images/icons/iconBill.webp',
    iconHistory: '/assets/images/icons/iconHistory.png',
    iconOrder: '/assets/images/icons/iconOrder.png',
    iconBack: '/assets/images/icons/iconBack.png',
    iconCart: '/assets/images/icons/iconCart.png',
    iconShield: '/assets/images/icons/iconShield.png',
    iconSupport: '/assets/images/icons/iconSupport.webp',
    iconResponsibility: '/assets/images/icons/iconResponsibility.webp',
    iconHeart: '/assets/images/icons/iconHeart.png',
    iconHeart1: '/assets/images/icons/iconHeart1.png',
    iconUpdating: '/assets/images/icons/iconUpdating.webp',
    iconSuccess: '/assets/images/icons/iconSuccess.png',
    iconShoppe: '/assets/images/icons/iconShoppe.png',
    messenger: '/assets/images/icons/iconMessager.png',
    iconDelete: '/assets/images/icons/iconDelete.png',
    iconFacebook: '/assets/images/icons/iconFaboook.png',
    iconChecked: '/assets/images/icons/iconChecked.png',
    iconSuccessGif: '/assets/images/icons/iconSuccess.gif',
    unknowTokenIcon: '/assets/images/icons/unknowTokenIcon.png',
    iconMessageChat: '/assets/images/icons/iconMessageChat.png',
  },
  home: {
    possCase: '/assets/images/Home/possCase.png',
  },
}
