export const POSS_CONFIG = {
  API_KEY: process.env.API_KEY,
  MERCHANT_ID_ETHEREUM: process.env.MERCHANT_ID_ETHEREUM,
  MERCHANT_ID_BASE: process.env.MERCHANT_ID_BASE,
  MERCHANT_ID_OPTIMISM: process.env.MERCHANT_ID_OPTIMISM,
  MERCHANT_ID_POLYGON: process.env.MERCHANT_ID_POLYGON,
  MERCHANT_ID_ARBITRUM: process.env.MERCHANT_ID_ARBITRUM,
}
